# Generated by Django 4.0.6 on 2022-07-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
