# Generated by Django 4.0.6 on 2022-07-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_botuserrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuserrequest',
            name='bot_user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='botuserrequest',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='botuserrequest',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
